sudo: false
language: go
go: 1.7

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - ./script/bootstrap -u

script:
  - go generate
  - ./script/build
  - ./script/test
  - ./script/coverage
  - ./script/lint

env:
  global:
    secure: "hbctOOj//8JEgTidYIn+mZ2uzYimGeFwmduUfnGcPpNk1fq7oUlfmXWItX+UU+Rfp2JbmC5LR3tStJLHRCXwabW2jiSsDntx7+iCU8L712tmP7aErRAhInlNsimyW2l/Vm5WfPPMfdO+/FXtBhYoMdtbPxKJuQlqEu3c/Hqvz9UTSwAaA7NPUCYQv951+E6Y0BYWhCJ8B5QvrRxyJGtU5Kt7c0maJ/nLDQYop2P5XGSUd22TFBIzx3VBrVszsev1i8nx3E9GJDqCK+j1uQQ12wyXAQvZOBKMuSBnUncHMBNgwOWYKL1KmegnOQh9FCDSEHK3PUVclVCv3yRQTA/9/QEP/LEhYVaPGFX1ABUT6eK0N79CAi7+ZsVPReFyqpjrOsInOri8dIHrTNepE2zlwE2OVK8AfemZseathQKEFFc7BV/qTVtn/v73a5k5eDP/0Lm+jqvc2Cw5/Yo56T6z/HArXfl3CwARWjPO1hx0jaaBALBB1AAJgDgkfLVb0Tnh8IVhkdLBGcQ7b1eY6unXoipD5XZhCi227UPDb20gE2vvix+Qsb+fF3z5AWyOXwxlzaUixfp0xwHD0oLBryZX7WWB/LDvv2hShWLBXX7Lp+JxjOrClTQSKdxp8IBN5+2gzYNKoLuqc344DjfsjJreUdBrXLT5P8wZSkby1p3sNzk="

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - ./script/build all
  - sha256sum docker-gc_* > checksums.sha256

after_deploy:
  - sleep 2
  - 'curl -k -H "Content-Type: application/json" --data ''{"source_type": "Tag", "source_name": "''"$TRAVIS_TAG"''"}'' -X POST "$DOCKER_HUB_TRIGGER_URL"'

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mTONRCd9AGM3cQ40pky3c2FLC/cer0mCi61EjXccjVmDeUAtMDuGEfkNG/aV0LVgWsExipJ471OshO2NkB36xU3Eh6l8frtf9GgCEkXbQIoKAC7RFh8sEsEZ78HehFDO2IY/ztwJpLG0BozQ7Bp9K+QdzcN5+Jfco10qz2rPEuFRbZpc8osfdL6EbxhrSNpOZva0SMyZlWtd0uW0VCkLPKn6Vtn7YX8dIyzQac2bC/ftL3qyGJfUQ1dHWXOIdY1y1VGyTnpqzwA4d4LG7gao5GJdpMW82XMFyNLq/ahsN3QmcdQFgrSQ3n2F8nwANhokyMQx9Jz01tfAnVgh8AlLQnuHxSvB+ahwPWr3B1RjV0V3qH2V+PPesUxd5mKfxoKVnFFmuEsAiaIWOC1QmRu6iVVpY8jdeyCfOgeTY6yY/nJY86nHp7IN0aPlO2cwuA9IlFXRytTz6Zoeks0z2/e6F60FPDwVjBuXFzhzn2SSEQbq5jDb57dvCVI/EIe6viNJsLSnIQJEWkbP3iPmXv81gA7+kyihDtnlA8XLayp3yrWaMEkV5DKPyChK0y5dEpiVVg5h+oc08f/GQin5hgiVhGOxJnw5caWd16kintBoFujJaCl/FzFkocZYaXnCjuftNZ8vtTGSycQrGp0DSwwEcSqLGNKBVuTOUwVinoU3CRc=
  file:
    - checksums.sha256
    - docker-gc_darwin_amd64
    - docker-gc_linux_amd64
    - docker-gc_linux_ppc64le
  on:
    tags: true
    repo: docwhat/docker-gc
