sudo: false
language: go
go: 1.6

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - ./script/bootstrap

script:
  - ./script/build
  - ./script/test
  - ./script/coverage
  - ./script/lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./script/release-container

env:
  global:
    - DOCKER_USER=docwhat
    - secure: "Wzjc7yjXkauFRBtbByafa5Th/Ivn6quuXVHLAsSarZ9+utcenwsvwX9GHQUsl2Us/0q7LQrJRE5PGXYZJSpiQXdrjSF/5fGJNuotwp2PeYuP2WOrRbhhzG83yoQqD0yKgMv+sgKXXeT87WYRgLd4W0O3jEv5pLgr+4vopJR4rIrjxq4GUzSp8xJSuuny+g5K8SVsvvQrd1s1LOlLWIdr+A2eEGiVstAcEKy9viztEmwppcwNaS6ig3O0mvTvhnWPHgZzZ7EgLVrNDg6gxzB/F+i+NFnYFiFztURCxaDz5+UQQnTx7WTcs4jcmFyqyKA84lSzZ6yF0H41BmW59K4ydRuvQ9QEvwOAW9ilPB00xGFQx8GdMMPERu3SENQ9yFitSm1GbziO8yuYYaVrBPVQwdJM0YDieLm6QAxH50nZI45stO4STJo9XTcOo2NQC0KuzPYSUfQ56f2horN8J3OcpLhCXuqee5Gj796l0d6w8UJG4uc/EV4LZ8DME8NqMy4JFqkIXvZ/Svz4tYZi3MNtHBJIEtOm7OAFeuCY0WuW0mOzq4YeIqHujrk4a0wt2fVFeJFIg0h2Yhdws1kPeFIGzApJgkM49EC+BewWeeCTTUfsB80CcIA/MUR2tx1QibAL0YbcVxuoQ0AMkcUNze2r1paH+0hqvbt7dyu+xXVi4iw=" # DOCKER_PASSWORD

before_deploy:
  - ./script/build all
  - sha256sum docker-gc_* > checksums.sha256

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mTONRCd9AGM3cQ40pky3c2FLC/cer0mCi61EjXccjVmDeUAtMDuGEfkNG/aV0LVgWsExipJ471OshO2NkB36xU3Eh6l8frtf9GgCEkXbQIoKAC7RFh8sEsEZ78HehFDO2IY/ztwJpLG0BozQ7Bp9K+QdzcN5+Jfco10qz2rPEuFRbZpc8osfdL6EbxhrSNpOZva0SMyZlWtd0uW0VCkLPKn6Vtn7YX8dIyzQac2bC/ftL3qyGJfUQ1dHWXOIdY1y1VGyTnpqzwA4d4LG7gao5GJdpMW82XMFyNLq/ahsN3QmcdQFgrSQ3n2F8nwANhokyMQx9Jz01tfAnVgh8AlLQnuHxSvB+ahwPWr3B1RjV0V3qH2V+PPesUxd5mKfxoKVnFFmuEsAiaIWOC1QmRu6iVVpY8jdeyCfOgeTY6yY/nJY86nHp7IN0aPlO2cwuA9IlFXRytTz6Zoeks0z2/e6F60FPDwVjBuXFzhzn2SSEQbq5jDb57dvCVI/EIe6viNJsLSnIQJEWkbP3iPmXv81gA7+kyihDtnlA8XLayp3yrWaMEkV5DKPyChK0y5dEpiVVg5h+oc08f/GQin5hgiVhGOxJnw5caWd16kintBoFujJaCl/FzFkocZYaXnCjuftNZ8vtTGSycQrGp0DSwwEcSqLGNKBVuTOUwVinoU3CRc=
  file:
    - checksums.sha256
    - docker-gc_darwin_amd64
    - docker-gc_linux_amd64
    - docker-gc_linux_ppc64le
  on:
    tags: true
    repo: docwhat/docker-gc
