#!/bin/bash
#
# Creates a minimal container from source.

set -euo pipefail
# shellcheck source=script/utilities.bash
source "$(dirname "$0")/utilities.bash"

version=$(git describe --tags --long)
version=${1:-$version}

./script/build docker

header "Building Container gc:${version}"
docker build --pull --tag="gc:${version}" --file=scratch.dockerfile .

# vim: set ft=sh :
