#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail
source "$(dirname "$0")/utilities.bash"

./script/build docker

header "Building Container"
docker build --pull --tag=docker-gc:latest .

# vim: set ft=sh :
