#!/bin/bash
#
# Generates a coverage report.

set -euo pipefail
# shellcheck source=script/utilities.bash
source "$(dirname "$0")/utilities.bash"

header "Building coverage"
govendor test \
  -race \
  -cover \
  -covermode=atomic \
  -coverprofile=coverage.txt \
  +local

# vim: set ft=sh :
