#!/bin/bash
#
# Runs the program.

set -euo pipefail
# shellcheck source=script/utilities.bash
source "$(dirname "$0")/utilities.bash"

typeset -a gofiles=()
for file in *.go; do
  if [[ "$file" != *_test.go ]]; then
    gofiles+=( "$file" )
  fi
done

go run "${gofiles[@]}" "$@"

# vim: set ft=sh :
