#!/bin/bash
#
# Runs all tests.

set -euo pipefail
source "$(dirname "$0")/utilities.bash"

header "Tests"
govendor test -v +local

header "Tests (race detection)"
govendor test -v -race +local

# vim: set ft=sh :
